on:
  push:
    branches:
      - master

env:
  NAME: mowork_app_web

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd /opt/server/${{ env.NAME }}
            git fetch --all
            git reset --hard origin/master
            git pull
            docker build -t ${{ env.NAME }} .
            docker run --name=${{ env.NAME }} -d -p 8080:80 ${{ env.NAME }}

